import React from 'react'; import { StyleSheet } from 'react-native'; import { MaterialCommunityIcons } from '@expo/vector-icons'; import { createBottomTabNavigator } from '@react-navigation/bottom-tabs'; import { createNativeStackNavigator } from '@react-navigation/native-stack'; import { getFocusedRouteNameFromRoute } from '@react-navigation/native';
import { ROUTES } from '../constants'; import { colors, controlHeights, typography } from '../theme';
import CoordinatorDashboardScreen from '../screens/coordinator/CoordinatorDashboardScreen'; import RequestQueueScreen from '../screens/coordinator/RequestQueueScreen'; import RequestVerificationScreen from '../screens/coordinator/RequestVerificationScreen'; import { BroadcastSuccessScreen, RequestRejectedScreen } from '../screens/coordinator/RequestDecisionScreen'; import DonorResponsesScreen from '../screens/coordinator/DonorResponsesScreen'; import DonorCheckInScreen from '../screens/coordinator/DonorCheckInScreen'; import BloodStockScreen from '../screens/coordinator/BloodStockScreen'; import CoordinatorProfileScreen from '../screens/coordinator/CoordinatorProfileScreen'; import CoordinatorChatScreen from '../screens/coordinator/CoordinatorChatScreen'; import CoordinatorCampsScreen from '../screens/coordinator/CoordinatorCampsScreen';
const Tabs=createBottomTabNavigator(),Dashboard=createNativeStackNavigator(),Requests=createNativeStackNavigator(),CheckIn=createNativeStackNavigator(),Stock=createNativeStackNavigator(),More=createNativeStackNavigator(); const opt={headerShown:false}; const hidden=new Set([ROUTES.REQUEST_VERIFICATION,ROUTES.REQUEST_BROADCAST,ROUTES.REQUEST_REJECTED,ROUTES.DONOR_RESPONSES,ROUTES.COORDINATOR_CHAT]);
const requestDetails=Stack=><React.Fragment><Stack.Screen name={ROUTES.REQUEST_VERIFICATION} component={RequestVerificationScreen}/><Stack.Screen name={ROUTES.REQUEST_BROADCAST} component={BroadcastSuccessScreen} options={{gestureEnabled:false}}/><Stack.Screen name={ROUTES.REQUEST_REJECTED} component={RequestRejectedScreen}/><Stack.Screen name={ROUTES.DONOR_RESPONSES} component={DonorResponsesScreen}/><Stack.Screen name={ROUTES.COORDINATOR_CHAT} component={CoordinatorChatScreen}/></React.Fragment>;
function DashboardNav(){return <Dashboard.Navigator screenOptions={opt}><Dashboard.Screen name={ROUTES.COORDINATOR_DASHBOARD} component={CoordinatorDashboardScreen}/>{requestDetails(Dashboard)}</Dashboard.Navigator>}; function RequestsNav(){return <Requests.Navigator screenOptions={opt}><Requests.Screen name={ROUTES.REQUEST_QUEUE} component={RequestQueueScreen}/>{requestDetails(Requests)}</Requests.Navigator>}; function CheckInNav(){return <CheckIn.Navigator screenOptions={opt}><CheckIn.Screen name={ROUTES.DONOR_CHECKIN} component={DonorCheckInScreen}/></CheckIn.Navigator>}; function StockNav(){return <Stock.Navigator screenOptions={opt}><Stock.Screen name={ROUTES.BLOOD_STOCK} component={BloodStockScreen}/></Stock.Navigator>}; function MoreNav(){return <More.Navigator screenOptions={opt}><More.Screen name={ROUTES.COORDINATOR_CAMPS} component={CoordinatorCampsScreen}/><More.Screen name={ROUTES.COORDINATOR_PROFILE} component={CoordinatorProfileScreen}/></More.Navigator>}
const icons={ [ROUTES.COORDINATOR_DASHBOARD_TAB]:['view-dashboard-outline','view-dashboard'],[ROUTES.COORDINATOR_REQUESTS_TAB]:['clipboard-text-outline','clipboard-text'],[ROUTES.COORDINATOR_CHECKIN_TAB]:['qrcode-scan','qrcode-scan'],[ROUTES.COORDINATOR_STOCK_TAB]:['water-outline','water'],[ROUTES.COORDINATOR_MORE_TAB]:['dots-horizontal-circle-outline','dots-horizontal-circle'] };
export default function CoordinatorNavigator(){return <Tabs.Navigator screenOptions={({route})=>{const f=getFocusedRouteNameFromRoute(route);return {headerShown:false,tabBarActiveTintColor:colors.primary,tabBarInactiveTintColor:colors.textTertiary,tabBarLabelStyle:s.label,tabBarStyle:[s.bar,hidden.has(f)&&s.hidden],tabBarIcon:({color,focused,size})=>{const n=icons[route.name];return <MaterialCommunityIcons name={focused?n[1]:n[0]} color={color} size={size}/>}}}}><Tabs.Screen name={ROUTES.COORDINATOR_DASHBOARD_TAB} component={DashboardNav} options={{title:'Dashboard'}}/><Tabs.Screen name={ROUTES.COORDINATOR_REQUESTS_TAB} component={RequestsNav} options={{title:'Requests'}}/><Tabs.Screen name={ROUTES.COORDINATOR_CHECKIN_TAB} component={CheckInNav} options={{title:'Check-in'}}/><Tabs.Screen name={ROUTES.COORDINATOR_STOCK_TAB} component={StockNav} options={{title:'Stock'}}/><Tabs.Screen name={ROUTES.COORDINATOR_MORE_TAB} component={MoreNav} options={{title:'Camps'}}/></Tabs.Navigator>}
const s=StyleSheet.create({bar:{alignSelf:'center',width:'100%',maxWidth:600,minHeight:controlHeights.bottomNavigation,paddingTop:6,borderTopColor:colors.border,backgroundColor:colors.surface},hidden:{display:'none'},label:{paddingBottom:5,fontSize:10,fontWeight:typography.weights.semibold}});
