import React, { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { AppHeader, Screen } from '../../components';
import { mockAcceptedRequest, mockHospitalChat } from '../../mocks/donorData';
import { colors, controlHeights, radius, spacing, typography } from '../../theme';

export default function HospitalChatScreen({ navigation }) {
  const [messages, setMessages] = useState([...mockHospitalChat]);
  const [draft, setDraft] = useState('');
  const send = () => { const text = draft.trim(); if (!text) return; setMessages((items) => [...items, { id: `local-${Date.now()}`, sender: 'donor', text, time: 'Now', delivered: true }]); setDraft(''); };
  return <Screen safeAreaEdges={['top', 'left', 'right', 'bottom']} padded={false}><View style={styles.shell}>
    <View style={styles.headerWrap}><AppHeader title={mockAcceptedRequest.hospital.name} subtitle={mockAcceptedRequest.coordinatorUnit} onBack={navigation.goBack} /></View>
    <View style={styles.notice}><MaterialCommunityIcons name="shield-check-outline" size={18} color={colors.info} /><Text style={styles.noticeText}>Preview chat · Messages are stored only on this device.</Text></View>
    <View style={styles.messages}>{messages.map((message) => message.sender === 'system' ? <View key={message.id} style={styles.system}><Text style={styles.systemText}>{message.text}</Text></View> : <View key={message.id} style={[styles.bubble, message.sender === 'donor' ? styles.mine : styles.theirs]}><Text style={[styles.messageText, message.sender === 'donor' && styles.mineText]}>{message.text}</Text><Text style={[styles.time, message.sender === 'donor' && styles.mineTime]}>{message.time}</Text></View>)}</View>
    <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.composer}><TextInput value={draft} onChangeText={setDraft} placeholder="Message the hospital" placeholderTextColor={colors.textTertiary} style={styles.input} multiline /><Pressable accessibilityRole="button" accessibilityLabel="Send message" disabled={!draft.trim()} onPress={send} style={({ pressed }) => [styles.send, (!draft.trim() || pressed) && styles.sendMuted]}><MaterialCommunityIcons name="send" size={21} color={colors.white} /></Pressable></View></KeyboardAvoidingView>
  </View></Screen>;
}
const styles = StyleSheet.create({ shell: { flex: 1, width: '100%', maxWidth: 600, alignSelf: 'center' }, headerWrap: { paddingHorizontal: spacing.xl, backgroundColor: colors.surface }, notice: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, padding: spacing.sm, backgroundColor: colors.infoSoft }, noticeText: { color: colors.info, fontSize: typography.sizes.caption }, messages: { flex: 1, padding: spacing.xl, gap: spacing.md }, system: { alignSelf: 'center', maxWidth: '90%', padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surfaceMuted }, systemText: { color: colors.textSecondary, fontSize: typography.sizes.caption, lineHeight: typography.lineHeights.caption, textAlign: 'center' }, bubble: { maxWidth: '82%', padding: spacing.md, borderRadius: radius.lg }, theirs: { alignSelf: 'flex-start', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, mine: { alignSelf: 'flex-end', backgroundColor: colors.primary }, messageText: { color: colors.textPrimary, fontSize: typography.sizes.supporting, lineHeight: typography.lineHeights.supporting }, mineText: { color: colors.white }, time: { marginTop: spacing.xs, color: colors.textTertiary, fontSize: 10 }, mineTime: { color: 'rgba(255,255,255,0.72)', textAlign: 'right' }, composer: { flexDirection: 'row', alignItems: 'flex-end', gap: spacing.sm, padding: spacing.md, borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: colors.surface }, input: { flex: 1, minHeight: controlHeights.touchTarget, maxHeight: 100, paddingHorizontal: spacing.lg, paddingVertical: spacing.md, borderWidth: 1, borderColor: colors.borderStrong, borderRadius: radius.xl, color: colors.textPrimary, fontSize: typography.sizes.supporting }, send: { width: controlHeights.touchTarget, height: controlHeights.touchTarget, borderRadius: radius.pill, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary }, sendMuted: { opacity: 0.55 } });
